name: Build, test and upload the module

on: [push, check_run]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.13.2
        platform:
          - gcc_64
          - android_arm64_v8a
          - android_x86_64
          - android_armv7
          - android_x86
          - wasm_32
          - msvc2017_64
          - msvc2017
          - winrt_x64_msvc2017
          - winrt_x86_msvc2017
          - winrt_armv7_msvc2017
          - mingw73_64
          - mingw73_32
          - clang_64
          - ios

        include:
          - platform: gcc_64
            os: ubuntu-latest
          - platform: android_arm64_v8a
            os: ubuntu-latest
          - platform: android_x86_64
            os: ubuntu-latest
          - platform: android_armv7
            os: ubuntu-latest
          - platform: android_x86
            os: ubuntu-latest
          - platform: wasm_32
            os: ubuntu-latest
            emsdk: sdk-1.38.27-64bit
          - platform: msvc2017_64
            os: windows-2016
            vcarch: x64
          - platform: msvc2017
            os: windows-2016
            vcarch: x64_x86
          - platform: winrt_x64_msvc2017
            os: windows-2016
            vcarch: x64
          - platform: winrt_x86_msvc2017
            os: windows-2016
            vcarch: x64_x86
          - platform: winrt_armv7_msvc2017
            os: windows-2016
            vcarch: x64_arm
          - platform: mingw73_64
            os: windows-latest
          - platform: mingw73_32
            os: windows-latest
          - platform: clang_64
            os: macos-latest
          - platform: ios
            os: macos-latest

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - name: actions/cache emsdk
        uses: actions/cache@v1
        if: matrix.platform == 'wasm_32'
        with:
          path: emsdk-cache
          key: ${{runner.os}}-emsdk-${{matrix.emsdk}}
      - uses: mymindstorm/setup-emsdk@v3
        if: matrix.platform == 'wasm_32'
        with:
          version: ${{matrix.emsdk}}
          actions-cache-folder: emsdk-cache
      - uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.platform, 'msvc')
        with:
          arch: ${{matrix.vcarch}}
          #toolset: 14.16
          uwp: ${{contains(matrix.platform, 'winrt')}}
      - name: actions/cache qt
        uses: actions/cache@v1
        id: cache
        with:
          path: qt/${{matrix.version}}/${{matrix.platform}}
          key: qt-${{matrix.version}}-${{matrix.platform}}
      - uses: Skycoder42/action-setup-qt@master
        id: qt
        with:
          version: ${{matrix.version}}
          platform: ${{matrix.platform}}
          install-args: --verbose
          cachedir: qt/${{matrix.version}}/${{matrix.platform}}
      - name: Install systemd deps
        if: matrix.platform == 'gcc_64'
        run: |
          sudo apt-get -qq install libsystemd-dev dbus-user-session
          export XDG_RUNTIME_DIR=/run/user/`id -u`
          export XDG_SESSION_ID=2
          sudo mkdir -p $XDG_RUNTIME_DIR
          sudo chown `id -un` $XDG_RUNTIME_DIR
          sudo systemctl start user@`id -u`.service
          echo "::set-env name=XDG_RUNTIME_DIR::$XDG_RUNTIME_DIR"
          echo "::set-env name=XDG_SESSION_ID::$XDG_SESSION_ID"
      - name: qmake
        run: |
          qmake CONFIG+=install_ok QT_PLATFORM=${{matrix.platform}}
          ${{steps.qt.outputs.make}} qmake_all
      - name: make module
        run: |
          ${{steps.qt.outputs.make}}
          ${{steps.qt.outputs.make}} INSTALL_ROOT="${{steps.qt.outputs.installdir}}" install
      - run: type ${{steps.qt.outputs.qtdir}}\bin\qt.conf
        if: contains(matrix.platform, 'msvc')
        continue-on-error: true
      - name: make tests
        if: steps.qt.outputs.tests == 'true' && !contains(matrix.platform, 'mingw')
        run: |
          ${{steps.qt.outputs.make}} all
          ${{steps.qt.outputs.make}} ${{steps.qt.outputs.testflags}} run-tests
      - name: make examples
        if: matrix.platform == 'gcc_64'
        run: |
          ${{steps.qt.outputs.make}} sub-examples
          cd examples && ${{steps.qt.outputs.make}} INSTALL_ROOT="${{steps.qt.outputs.installdir}}" install
      - name: make doc
        if: matrix.platform == 'gcc_64'
        run: |
          ${{steps.qt.outputs.make}} doxygen
          cd doc && ${{steps.qt.outputs.make}} INSTALL_ROOT="${{steps.qt.outputs.installdir}}" install
      - name: upload module to releases
        uses: Skycoder42/action-upload-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          directory: ${{steps.qt.outputs.outdir}}/${{matrix.version}}
          asset_name: qtservice-${{matrix.platform}}-${{matrix.version}}
          tag: ${{github.ref}}
          overwrite: true
      - name: upload examples to releases
        uses: Skycoder42/action-upload-release@master
        if: matrix.platform == 'gcc_64' && startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          directory: ${{steps.qt.outputs.outdir}}/Examples
          asset_name: qtservice-examples-${{matrix.version}}
          tag: ${{github.ref}}
          overwrite: true
      - name: upload doc to releases
        uses: Skycoder42/action-upload-release@master
        if: matrix.platform == 'gcc_64' && startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          directory: ${{steps.qt.outputs.outdir}}/Docs
          asset_name: qtservice-doc-${{matrix.version}}
          tag: ${{github.ref}}
          overwrite: true

  deploy:
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - name: Deploy releases
        run: echo "Hello World"
